#!/usr/bin/env bash
set -e # halt script on error

function msg {
  printf "\e[0;37m==> $1\e[0m\n"
}

DESTINATION="_site"

IGNORE_HREFS=$(ruby -e 'puts %w{
  canonical.com
  en.gravatar.com
  github.com\/jjasghar
  githubusercontent.com
  jjasghar.github.io
  localhost
}.map{|h| "/#{h}/"}.join(",")')

bundle exec jekyll build
#bundle exec htmlproofer ./$DESTINATION --allow-hash-href --url-ignore $IGNORE_HREFS --alt-ignore '/.*/' $@
